import comfy.model_management as model_management
import torch
from comfy_api.latest import io
from comfy_extras.nodes_depth_anything_3 import DA3ModelType

from .depth import estimate_da3_guidance, render_guidance_depth
from .engine import QUALITY_OPTIONS, DLSS5Engine
from .postprocess import cas_sharpen
from .types import DLSSGuidance


DLSSGuidanceType = io.Custom("BOKUJUU_DLSS_GUIDANCE")
INTERNAL_CONSTANT_DEPTH = 0.5


def _constant_guidance(images):
    return DLSSGuidance(
        depth=torch.full(
            tuple(images.shape[:3]),
            INTERNAL_CONSTANT_DEPTH,
            dtype=torch.float32,
            device="cpu",
        )
    ).validate_for(images)


def _common_inputs(include_scene_cut=False):
    inputs = [
        io.Image.Input("images"),
        io.Float.Input("scale", default=2.0, min=1.0, max=3.0, step=0.5),
        io.Combo.Input(
            "quality",
            options=list(QUALITY_OPTIONS),
            default="balanced",
            tooltip="Ordered from fastest/lowest quality to slowest/highest quality. DLAA is 1.0x only. Ultra Quality may be rejected at 2.0x.",
        ),
        io.Float.Input(
            "cas_amount",
            default=0.7,
            min=0.0,
            max=4.0,
            step=0.05,
            tooltip="Contrast Adaptive Sharpening after DLSS-SR. 0 disables it. Values above 1 are experimental.",
        ),
        io.Float.Input("output_mix", default=1.0, min=0.0, max=1.0, step=0.05),
    ]
    if include_scene_cut:
        inputs.append(
            io.Float.Input(
                "scene_cut_threshold",
                default=0.35,
                min=0.0,
                max=1.0,
                step=0.01,
                tooltip="Reset temporal history when mean frame difference reaches this value; 0 disables detection.",
            )
        )
    inputs.append(io.Int.Input("gpu_index", default=0, min=0, max=15))
    return inputs


class BokujuuDLSSGuidanceDepth(io.ComfyNode):
    @classmethod
    def define_schema(cls):
        return io.Schema(
            node_id="BokujuuDLSSGuidanceDepth",
            display_name="Bokujuu DLSS Guidance Depth (DA3)",
            category="Bokujuu/DLSS",
            description="Estimates the relative DA3 depth supplied as DLSS guidance. This depth is not generated by DLSS.",
            inputs=[
                DA3ModelType.Input("da3_model"),
                io.Image.Input("images"),
                io.Int.Input("resolution", default=504, min=140, max=2520, step=14),
                io.Combo.Input(
                    "resize_method",
                    options=["upper_bound_resize", "lower_bound_resize"],
                    default="upper_bound_resize",
                ),
                io.Combo.Input(
                    "normalization",
                    options=["v2_style", "min_max"],
                    default="v2_style",
                ),
                io.Combo.Input(
                    "color_theme",
                    options=["grayscale", "grayscale_inverted", "turbo", "viridis", "plasma", "inferno"],
                    default="grayscale",
                ),
                io.Float.Input("contrast", default=1.0, min=0.0, max=3.0, step=0.05),
                io.Float.Input("gamma", default=1.0, min=0.1, max=5.0, step=0.05),
            ],
            outputs=[
                io.Image.Output(display_name="depth_image"),
                DLSSGuidanceType.Output(display_name="guidance"),
            ],
        )

    @classmethod
    def execute(
        cls,
        da3_model,
        images,
        resolution,
        resize_method,
        normalization,
        color_theme,
        contrast,
        gamma,
    ):
        guidance = estimate_da3_guidance(
            da3_model,
            images,
            resolution=resolution,
            resize_method=resize_method,
            normalization=normalization,
        )
        return io.NodeOutput(
            render_guidance_depth(guidance, color_theme, contrast, gamma), guidance
        )


class BokujuuDLSS5NeuralUpscale(io.ComfyNode):
    @classmethod
    def define_schema(cls):
        return io.Schema(
            node_id="BokujuuDLSS5NeuralUpscale",
            display_name="Bokujuu DLSS 5 Neural Upscale",
            category="Bokujuu/DLSS",
            description="Experimental true DLSS Super Resolution upscale. Uses internal constant depth 0.5; default is Balanced plus CAS 0.7.",
            inputs=_common_inputs(),
            outputs=[io.Image.Output(display_name="upscaled_images")],
        )

    @classmethod
    def execute(cls, images, scale, quality, cas_amount, output_mix, gpu_index):
        guidance = _constant_guidance(images)
        model_management.unload_all_models()
        output = DLSS5Engine(gpu_index=gpu_index).enhance_image(
            images, guidance, scale=scale, quality=quality, output_mix=output_mix
        )
        return io.NodeOutput(cas_sharpen(output, amount=cas_amount))


class BokujuuDLSS5TemporalUpscale(io.ComfyNode):
    @classmethod
    def define_schema(cls):
        return io.Schema(
            node_id="BokujuuDLSS5TemporalUpscale",
            display_name="Bokujuu DLSS 5 Temporal Upscale",
            category="Bokujuu/DLSS",
            description="Processes an IMAGE batch in one DLSS-SR temporal session. Uses internal constant depth 0.5; default is Balanced plus CAS 0.7.",
            inputs=_common_inputs(include_scene_cut=True),
            outputs=[io.Image.Output(display_name="upscaled_frames")],
        )

    @classmethod
    def execute(
        cls,
        images,
        scale,
        quality,
        cas_amount,
        output_mix,
        scene_cut_threshold,
        gpu_index,
    ):
        guidance = _constant_guidance(images)
        model_management.unload_all_models()
        output = DLSS5Engine(gpu_index=gpu_index).enhance_sequence(
            images,
            guidance,
            scale=scale,
            quality=quality,
            output_mix=output_mix,
            scene_cut_threshold=scene_cut_threshold,
        )
        return io.NodeOutput(cas_sharpen(output, amount=cas_amount))
