from dataclasses import dataclass

import torch


@dataclass(frozen=True)
class DLSSGuidance:
    """Estimated guidance supplied to DLSS; it is not generated by DLSS."""

    depth: torch.Tensor | None = None
    motion: torch.Tensor | None = None
    exposure: torch.Tensor | None = None
    reactive_mask: torch.Tensor | None = None

    def validate_for(self, images: torch.Tensor) -> "DLSSGuidance":
        if self.depth is not None:
            expected = tuple(images.shape[:3])
            if tuple(self.depth.shape) != expected:
                raise ValueError(
                    f"DLSS guidance depth must have shape {expected}; got {tuple(self.depth.shape)}"
                )
            if not torch.isfinite(self.depth).all():
                raise ValueError("DLSS guidance depth contains NaN or infinite values")
        return self
